spring:
  datasource:
    url: jdbc:postgresql://ec2-54-160-18-230.compute-1.amazonaws.com:5432/d94umncm6504kr
    username: khxnjapcfyaqbv
    password: 6e48350ef302176fc5cc3ee77b04f21021b285d861772c82a366b6bce2123dba
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      #ddl-auto: create-drop # Para que cree las tablas automaticamente si no existe
      ddl-auto: update # Para actualizar las tablas sin necesidad de borrarlas
      generate-ddl: true # Para que imprima en sql las transformaciones a sql
    show-sql: true  # Para que imprima en sql las transformaciones a sql